LATENT_DIMENSION = 128 
EPOCHS = 100 
BATCH_SIZE = 128 
VALIDATION_SPLIT = 0.001  

RATING_STATISTICS_PATH = './rating_statistics.npy' 
MATRIX_FACTORIZATION_CHECKPOINT_PATH = './matrix_factorization.hdf5' 

